In [4]:
import numpy as np
import math

In [3]:
arr = np.random.rand(5,5)
arr

array([[0.97830163, 0.32553557, 0.80114583, 0.39793852, 0.56571009],
       [0.53227131, 0.16119552, 0.17401277, 0.21817712, 0.93152337],
       [0.51958306, 0.26963291, 0.49932887, 0.21793043, 0.40783371],
       [0.49746736, 0.394764  , 0.85498798, 0.10874626, 0.40066614],
       [0.15992337, 0.7955068 , 0.22388516, 0.81832619, 0.38528776]])

### element-wise addition, subtraction, multiplication and division

In [ ]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.76303985 10.06149651 10.57904337 10.8291741  10.34909157]
 [10.79875216 10.81553256 10.33263298 10.94754927 10.26929677]
 [10.91324204 10.36290234 10.47837507 10.11076725 10.1412222 ]
 [10.41560224 10.08529364 10.60372547 10.02257422 10.44915824]
 [10.35742146 10.74715734 10.65180952 10.9195904  10.02214632]]
[[-9.23696015 -9.93850349 -9.42095663 -9.1708259  -9.65090843]
 [-9.20124784 -9.18446744 -9.66736702 -9.05245073 -9.73070323]
 [-9.08675796 -9.63709766 -9.52162493 -9.88923275 -9.8587778 ]
 [-9.58439776 -9.91470636 -9.39627453 -9.97742578 -9.55084176]
 [-9.64257854 -9.25284266 -9.34819048 -9.0804096  -9.97785368]]
[[7.63039852 0.61496507 5.79043373 8.29174099 3.49091569]
 [7.98752158 8.15532564 3.32632975 9.47549269 2.69296773]
 [9.13242041 3.62902344 4.78375066 1.10767253 1.41222201]
 [4.15602235 0.85293636 6.03725474 0.22574224 4.49158239]
 [3.57421456 7.47157342 6.51809517 9.19590397 0.22146316]]
[[0.07630399 0.00614965 0.05790434 0.08291741 0.03490916]
 [0.07987522 0.0815

In [ ]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


### element-wise exponentiation

In [ ]:
print(np.exp(arr))

[[2.14478615 1.06342678 1.78433068 2.29142547 1.41777901]
 [2.22276554 2.26037915 1.39463534 2.57938054 1.30904357]
 [2.49238988 1.43749547 1.61345052 1.11713487 1.15168052]
 [1.51528302 1.0890368  1.82891972 1.02283095 1.5669926 ]
 [1.42963827 2.11099066 1.91901017 2.50826279 1.02239337]]


### element-wise logorithm

In [ ]:
# natural log
print(np.log(arr))

[[-0.27044502 -2.78877489 -0.54637789 -0.18732513 -1.05242102]
 [-0.22470457 -0.20391393 -1.10071557 -0.05387634 -1.31194126]
 [-0.09075433 -1.01362151 -0.7373602  -2.2003241  -1.95742073]
 [-0.87802664 -2.46165544 -0.5046357  -3.79094655 -0.80038003]
 [-1.02883965 -0.29147948 -0.42800291 -0.08382693 -3.81008411]]


In [ ]:
# base 2
print(np.log2(arr))

[[-0.39016969 -4.02335171 -0.78825668 -0.27025304 -1.51832258]
 [-0.32418017 -0.29418561 -1.5879969  -0.07772714 -1.89273115]
 [-0.13093082 -1.46234672 -1.0637859  -3.17439666 -2.82396118]
 [-1.26672468 -3.55141809 -0.72803542 -5.46917978 -1.1547043 ]
 [-1.48430185 -0.42051601 -0.61747768 -0.12093669 -5.49678945]]


In [ ]:
# base 10
print(np.log10(arr))

[[-0.11745278 -1.21114955 -0.2372889  -0.08135427 -0.45706064]
 [-0.09758796 -0.08855869 -0.4780347  -0.0233982  -0.56976885]
 [-0.0394141  -0.44021023 -0.32023147 -0.95558861 -0.85009702]
 [-0.38132213 -1.06908337 -0.2191605  -1.64638717 -0.34760063]
 [-0.44681938 -0.12658793 -0.1858793  -0.03640557 -1.65469851]]


### element-wise square root

In [ ]:
print(np.sqrt(arr))

[[0.87352152 0.24798489 0.76094899 0.91058997 0.59083971]
 [0.89372935 0.90306842 0.57674342 0.97342142 0.51893812]
 [0.95563698 0.60241376 0.69164663 0.33281715 0.37579542]
 [0.64467219 0.29205074 0.77699773 0.15024721 0.67019269]
 [0.59784735 0.86438264 0.80734721 0.95895276 0.14881638]]


### element-wise sine and cosine

In [ ]:
print(np.sin(arr))

[[0.69112165 0.06145775 0.5472235  0.73737374 0.34204431]
 [0.71648615 0.72809076 0.32653281 0.81198751 0.26605362]
 [0.79148938 0.35498904 0.46033726 0.11054088 0.14075325]
 [0.40374097 0.08519025 0.56771331 0.02257231 0.43420742]
 [0.34985981 0.67955607 0.60662594 0.79535341 0.02214451]]


In [ ]:
print(np.cos(arr))

[[0.72273845 0.99810969 0.83698652 0.67548499 0.93968382]
 [0.69760131 0.68548074 0.94518587 0.5836748  0.96395823]
 [0.61118293 0.93487046 0.88774411 0.99387158 0.99004471]
 [0.91487334 0.9963647  0.82322633 0.99974521 0.90081292]
 [0.93680207 0.73362358 0.7949874  0.60614599 0.99975478]]


### sum along a specified axis

In [ ]:
# sum along the row
print(np.sum(arr, axis=0))

[3.24805774 2.07238239 2.64558641 2.82965524 1.2309151 ]


In [ ]:
# sum along the column
print(np.sum(arr, axis=1))

[2.5818454  3.16376374 2.0065089  1.57635381 2.69812503]


### compute the min and max along a specified axis

In [ ]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.35742146 0.06149651 0.33263298 0.02257422 0.02214632]


In [ ]:
# calculate max along the column
print(np.max(arr, axis=1))

[0.8291741  0.94754927 0.91324204 0.60372547 0.9195904 ]


In [ ]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

0.9475492686719678
0.022146316110606912


### compute the indices of the min and max along a specified axis

In [7]:
arr

array([[0.97830163, 0.32553557, 0.80114583, 0.39793852, 0.56571009],
       [0.53227131, 0.16119552, 0.17401277, 0.21817712, 0.93152337],
       [0.51958306, 0.26963291, 0.49932887, 0.21793043, 0.40783371],
       [0.49746736, 0.394764  , 0.85498798, 0.10874626, 0.40066614],
       [0.15992337, 0.7955068 , 0.22388516, 0.81832619, 0.38528776]])

In [11]:
# along the row
print(np.argmin(arr, axis=1))


[1 1 3 3 0]


In [12]:
print(np.argmax(arr, axis=1))

[0 4 0 2 3]


In [9]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[1 1 3 3 0]
[0 4 0 2 3]


In [ ]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

24
8


### compute element-wise min and max of two arrays

In [ ]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [ ]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.21779326 0.58882555 0.32195097 0.45853207 0.50994103 0.42358094
 0.32348379 0.31232886 0.16890174 0.49021443]
integral:  [0. 0. 5. 5. 5. 1. 2. 1. 6. 8.]


### compute the mean

In [ ]:
# compute the overall mean
print(np.mean(arr))

0.4810638752799312


In [ ]:
# compute the mean along the row
print(np.mean(arr, axis=0))

[0.64961155 0.41447648 0.52911728 0.56593105 0.24618302]


In [13]:
arr


array([[0.97830163, 0.32553557, 0.80114583, 0.39793852, 0.56571009],
       [0.53227131, 0.16119552, 0.17401277, 0.21817712, 0.93152337],
       [0.51958306, 0.26963291, 0.49932887, 0.21793043, 0.40783371],
       [0.49746736, 0.394764  , 0.85498798, 0.10874626, 0.40066614],
       [0.15992337, 0.7955068 , 0.22388516, 0.81832619, 0.38528776]])

In [14]:
# compute the mean along the column
print(np.mean(arr, axis=0))

[0.53750935 0.38932696 0.51067212 0.3522237  0.53820422]


### compute the median

In [ ]:
# compute the overall median
print(np.median(arr))

0.4491582392434029


In [ ]:
# compute the median along the row
print(np.median(arr, axis=0))

[0.76303985 0.36290234 0.57904337 0.8291741  0.26929677]


In [ ]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.57904337 0.79875216 0.36290234 0.41560224 0.65180952]


### compute the percentile

In [ ]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.02821037 0.5914621  0.89273939]


### compute the standard deviation & variance

In [ ]:
# compute the overall standard deviation
print(np.std(arr))

0.3006485476445816


In [ ]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.22124437 0.3184772  0.11339598 0.41046681 0.15068681]


In [ ]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.28196182 0.27648987 0.29036161 0.22349905 0.31654733]


In [ ]:
# compute the overall variance
print(np.var(arr))

0.09038954920079624


In [ ]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.04894907 0.10142773 0.01285865 0.168483   0.02270651]


In [ ]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.07950247 0.07644665 0.08430987 0.04995182 0.10020221]


### compute the covariance & correlation

In [ ]:
arr = np.random.rand(5,8)

In [ ]:
print(np.cov(arr))

[[ 0.0730498   0.04997737 -0.00836842  0.00865103 -0.03076003]
 [ 0.04997737  0.06921278 -0.02750488  0.0401044  -0.04116094]
 [-0.00836842 -0.02750488  0.05298148 -0.04966884  0.03063382]
 [ 0.00865103  0.0401044  -0.04966884  0.06762098 -0.02100972]
 [-0.03076003 -0.04116094  0.03063382 -0.02100972  0.07502637]]


In [ ]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[1.         0.11028402]
 [0.11028402 1.        ]]


### compute cumulative sum & product

In [ ]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))

[[0.22630778 0.767801   0.58288104 0.91212964 0.16866086 0.71225777
  0.75992693 0.43036535]
 [0.59072776 1.41363555 1.26836278 1.39281883 0.17541256 1.09197627
  1.56096648 0.6397989 ]
 [0.86915997 1.77345229 1.64305337 2.01662839 0.70369834 1.28990428
  1.86675912 1.54481741]
 [1.73953799 2.39132679 2.30715387 2.2988209  0.89970976 2.05231818
  2.61580011 1.82762798]
 [2.73272009 3.02599488 2.8500615  3.11255427 1.53154629 2.58196071
  2.74551764 2.76644411]]


In [ ]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))

[[0.22630778 0.99410878 1.57698982 2.48911946 2.65778031 3.37003808
  4.12996501 4.56033036]
 [0.36441999 1.01025454 1.69573627 2.17642546 2.18317717 2.56289567
  3.36393522 3.57336877]
 [0.2784322  0.63824894 1.01293953 1.6367491  2.16503487 2.36296289
  2.66875553 3.57377405]
 [0.87037803 1.48825253 2.15235303 2.43454554 2.63055696 3.39297085
  4.14201184 4.42482241]
 [0.9931821  1.62785019 2.17075782 2.98449119 3.61632772 4.14597025
  4.27568777 5.2145039 ]]


In [ ]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))

[[2.26307776e-01 7.67801004e-01 5.82881038e-01 9.12129639e-01
  1.68660858e-01 7.12257767e-01 7.59926931e-01 4.30365348e-01]
 [8.24710772e-02 4.95872414e-01 3.99554306e-01 4.38450855e-01
  1.13874845e-03 2.70457451e-01 6.08731528e-01 9.01329430e-02]
 [2.29626035e-02 1.78423193e-01 1.49709241e-01 2.73509837e-01
  6.01584614e-04 5.35311066e-02 1.86145622e-01 8.15719823e-02]
 [1.99861456e-02 1.10243142e-01 9.94219814e-02 7.71824276e-02
  1.17917453e-04 4.08128596e-02 1.39430701e-01 2.30694183e-02]
 [1.98498821e-02 6.99678041e-02 5.39769526e-02 6.28059168e-02
  7.45045544e-05 2.16162260e-02 1.80866051e-02 2.16579420e-02]]


In [ ]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))

[[2.26307776e-01 1.73759338e-01 1.01281023e-01 9.23814230e-02
  1.55811300e-02 1.10977809e-02 8.43350257e-03 3.62948727e-03]
 [3.64419989e-01 2.35355019e-01 1.61331567e-01 7.75503399e-02
  5.23597062e-04 1.98819491e-04 1.59262276e-04 3.33548640e-05]
 [2.78432201e-01 1.00184566e-01 3.75382145e-02 2.34166972e-02
  1.23707081e-02 2.44850971e-03 7.48736253e-04 6.77620172e-04]
 [8.70378028e-01 5.37784391e-01 3.57142882e-01 1.00783047e-01
  1.97546278e-02 1.50612027e-02 1.12814582e-02 3.19051555e-03]
 [9.93182100e-01 6.30340985e-01 3.42216932e-01 2.78473337e-01
  1.75949628e-01 9.31904051e-02 1.20884285e-02 1.13488117e-02]]


### element-wise comparison

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [ ]:
# return an array of bools
print(arr1 == arr2)
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]
