In [1]:
import numpy as np

In [2]:
b_arr=np.random.randint(100,1000,size=(11,11))
b_arr

array([[718, 868, 582, 652, 703, 260, 164, 633, 462, 632, 714],
       [420, 248, 462, 689, 649, 946, 156, 838, 599, 611, 998],
       [265, 473, 547, 607, 955, 705, 241, 438, 332, 705, 159],
       [692, 657, 636, 596, 521, 596, 901, 212, 138, 136, 365],
       [682, 154, 789, 661, 617, 797, 320, 621, 526, 449, 280],
       [267, 420, 629, 986, 645, 795, 120, 146, 635, 882, 864],
       [773, 529, 842, 115, 172, 871, 960, 866, 901, 579, 647],
       [786, 461, 456, 556, 752, 927, 222, 779, 990, 165, 314],
       [259, 750, 911, 750, 901, 631, 767, 828, 887, 999, 439],
       [366, 371, 787, 797, 128, 329, 317, 837, 994, 272, 447],
       [231, 259, 576, 345, 840, 976, 566, 843, 232, 624, 146]])

In [7]:

# syntax for indexing----[row_num,col_num]
b_arr[10,10]

146

In [ ]:
# syntax for slicing---[start_row_num:stop_row_num:step,start_col_num:stop_col_num:step]

In [26]:
b_arr[5:2:-1,-1::-1]

array([[864, 882, 635, 146, 120, 795, 645, 986, 629, 420, 267],
       [280, 449, 526, 621, 320, 797, 617, 661, 789, 154, 682],
       [365, 136, 138, 212, 901, 596, 521, 596, 636, 657, 692]])

In [5]:
b_arr[0,-4:-8:-1]

array([633, 164, 260, 703])

In [ ]:
arr = np.array(range(100)).reshape((10,10))

### select an element by row and column indices

In [ ]:
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


### indexing with slicing

In [ ]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [ ]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# equivalent to arr[0,:,:,:]
print(arr[0, ...])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### assign a scalar to a slice by broadcasting

In [28]:
b_arr

array([[718, 868, 582, 652, 703, 260, 164, 633, 462, 632, 714],
       [420, 248, 462, 689, 649, 946, 156, 838, 599, 611, 998],
       [265, 473, 547, 607, 955, 705, 241, 438, 332, 705, 159],
       [692, 657, 636, 596, 521, 596, 901, 212, 138, 136, 365],
       [682, 154, 789, 661, 617, 797, 320, 621, 526, 449, 280],
       [267, 420, 629, 986, 645, 795, 120, 146, 635, 882, 864],
       [773, 529, 842, 115, 172, 871, 960, 866, 901, 579, 647],
       [786, 461, 456, 556, 752, 927, 222, 779, 990, 165, 314],
       [259, 750, 911, 750, 901, 631, 767, 828, 887, 999, 439],
       [366, 371, 787, 797, 128, 329, 317, 837, 994, 272, 447],
       [231, 259, 576, 345, 840, 976, 566, 843, 232, 624, 146]])

In [31]:
b__arr=b_arr[:1,5:2:-1]=200
b_arr

array([[718, 868, 582, 200, 200, 200, 164, 633, 462, 632, 714],
       [420, 248, 462, 689, 649, 946, 156, 838, 599, 611, 998],
       [265, 473, 547, 607, 955, 705, 241, 438, 332, 705, 159],
       [692, 657, 636, 596, 521, 596, 901, 212, 138, 136, 365],
       [682, 154, 789, 661, 617, 797, 320, 621, 526, 449, 280],
       [267, 420, 629, 986, 645, 795, 120, 146, 635, 882, 864],
       [773, 529, 842, 115, 172, 871, 960, 866, 901, 579, 647],
       [786, 461, 456, 556, 752, 927, 222, 779, 990, 165, 314],
       [259, 750, 911, 750, 901, 631, 767, 828, 887, 999, 439],
       [366, 371, 787, 797, 128, 329, 317, 837, 994, 272, 447],
       [231, 259, 576, 345, 840, 976, 566, 843, 232, 624, 146]])

In [ ]:
b__arr=b_arr[:1,5:2:-1]=200
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print(arr)

[[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


### boolean indexing

In [32]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [33]:
# negate the condition
print(arr1[~bools])

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [35]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print([(arr2<2) ])

[array([ True, False, False, False, False])]


### fancy indexing

In [ ]:
arr = np.random.rand(10,10)

In [ ]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])

[0.29404208 0.06137223 0.59811053]


In [ ]:
# select rows 3,1,2 and columns 6,4,8
print(arr[[3,1,2]][:, [6,4,8]])

[[0.09566854 0.2190723  0.6754328 ]
 [0.28997889 0.13675444 0.07718654]
 [0.15862308 0.45510309 0.94789792]]


### dimension inference

In [ ]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


### find elements/indices by conditions

In [52]:
# 2D shape
arr = np.arange(16).reshape(4,4)
print(arr.T)  # transpose of a matrix

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [50]:
arr = np.arange(16).reshape(-1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
# 1D
arr = np.arange(16).reshape(16,1)
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [ ]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [ ]:
# return values based on conditions
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [ ]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
